#!/usr/bin/env python3
"""Build phase25 Simple Studio es-419 translations (informal tú)."""

from __future__ import annotations

import json
from pathlib import Path

OUT = Path(__file__).resolve().parents[2] / "docs/localization/phase25-simple-studio.json"

# English key -> es-419 (es-ES often same for LATAM informal product copy)
PAIRS: dict[str, str] = {
    "Who owes me?": "¿Quién me debe?",
    "Waiting on payment": "Esperando pago",
    "What do I owe?": "¿Qué debo?",
    "They owe me": "Me deben",
    "Jobs this month": "Trabajos este mes",
    "Invoices waiting": "Facturas pendientes",
    "Expenses this week": "Gastos esta semana",
    "Money in this month": "Dinero entrante este mes",
    "What did I spend?": "¿En qué gasté?",
    "Paid this month": "Pagado este mes",
    "Unpaid jobs": "Trabajos sin pagar",
    "People I work with": "Personas con las que trabajo",
    "Income last month": "Ingresos el mes pasado",
    "Expenses today": "Gastos hoy",
    "Find a customer": "Buscar cliente",
    "Who paid me?": "¿Quién me pagó?",
    "Settled debts": "Deudas saldadas",
    "Work done this week": "Trabajo hecho esta semana",
    "Who owes me? Jobs for Maria…": "¿Quién me debe? Trabajos de María…",
    "Works offline — search people, jobs, invoices, and who still owes you.": "Funciona sin internet: busca personas, trabajos, facturas y quién te debe.",
    "People": "Personas",
    "Upgrade to Pro": "Pasar a Pro",
    "Work clock": "Reloj de trabajo",
    "Quote job": "Cotizar trabajo",
    "Log money": "Registrar dinero",
    "Invoice": "Factura",
    "Business card": "Tarjeta de presentación",
    "They owe me": "Me deben",
    "I owe": "Debo",
    "Close menu": "Cerrar menú",
    "Add": "Agregar",
    "Mark as paid?": "¿Marcar como pagado?",
    "Mark as settled?": "¿Marcar como saldado?",
    "Mark paid": "Marcar pagado",
    "Mark settled": "Marcar saldado",
    "Cancel": "Cancelar",
    "This will mark the balance as fully paid.": "Esto marcará el saldo como pagado por completo.",
    "This clears what you owe them.": "Esto liquida lo que les debes.",
    "Waiting on": "Esperando",
    "Paid": "Pagado",
    "Send": "Enviar",
    "You owe": "Debes",
    "Settled": "Saldado",
    "Recent": "Reciente",
    "Made": "Ingresos",
    "Waiting": "Pendiente",
    "I owe": "Debo",
    "This month": "Este mes",
    "Clear filter": "Quitar filtro",
    "Job pockets": "Bolsillos por trabajo",
    "Not paid yet": "Aún no pagado",
    "Type": "Tipo",
    "Amount": "Monto",
    "Who": "Quién",
    "Job": "Trabajo",
    "Note": "Nota",
    "Customer name": "Nombre del cliente",
    "What was it for?": "¿Para qué fue?",
    "Optional": "Opcional",
    "Job costs": "Costos del trabajo",
    "Materials": "Materiales",
    "Petrol / gas": "Gasolina",
    "Transport": "Transporte",
    "Platform fee": "Comisión de plataforma",
    "Details": "Detalles",
    "Payment": "Pago",
    "When": "Cuándo",
    "Mark paid": "Marcar pagado",
    "Mark settled": "Marcar saldado",
    "Entry not found": "Entrada no encontrada",
    "This entry may have been removed.": "Esta entrada pudo haberse eliminado.",
    "Tap to add": "Toca para agregar",
    "Still waiting": "Aún esperando",
    "Partial": "Parcial",
    "Scan failed": "Falló el escaneo",
    "Could not read this image. Try a clearer photo or enter details manually.": "No pudimos leer esta imagen. Prueba una foto más clara o ingresa los datos manualmente.",
    "OK": "OK",
    "Reading photo…": "Leyendo foto…",
    "Take photo": "Tomar foto",
    "Simulate scan": "Simular escaneo",
    "Choose from photos": "Elegir de fotos",
    "Tap to fix": "Toca para corregir",
    "Save to ledger": "Guardar en libro",
    "Update entry": "Actualizar entrada",
    "What is this?": "¿Qué es esto?",
    "Customer or merchant": "Cliente o comercio",
    "Job or description": "Trabajo o descripción",
    "Optional details": "Detalles opcionales",
    "Payment status": "Estado de pago",
    "Status": "Estado",
    "We couldn't read text from that image. Try better lighting, a sharper photo, or use Simulate scan to practice.": "No leímos texto en esa imagen. Mejor luz, foto más nítida, o usa Simular escaneo para practicar.",
    "Paid?": "¿Pagado?",
    "Customer": "Cliente",
    "How do you get paid?": "¿Cómo te pagan?",
    "Pay type": "Tipo de pago",
    "How long should it take?": "¿Cuánto debería tardar?",
    "Hours": "Horas",
    "Minutes": "Minutos",
    "Save job": "Guardar trabajo",
    "Update job": "Actualizar trabajo",
    "Send quote": "Enviar cotización",
    "Paid so far": "Pagado hasta ahora",
    "Advance for materials": "Anticipo de materiales",
    "Materials purchased": "Materiales comprados",
    "Agreed with customer": "Acordado con el cliente",
    "Spent on job": "Gastado en el trabajo",
    "Still waiting": "Aún pendiente",
    "You keep (so far)": "Te quedas (hasta ahora)",
    "You'll keep (when paid)": "Te quedarás (al pagar)",
    "Name": "Nombre",
    "Phone / WhatsApp": "Teléfono / WhatsApp",
    "What is the work?": "¿Cuál es el trabajo?",
    "Full price you agreed": "Precio total acordado",
    "Your rate per hour": "Tu tarifa por hora",
    "Ballpark total (optional)": "Total aproximado (opcional)",
    "Still waiting": "Aún pendiente",
    "Partially paid": "Pagado en parte",
    "Paid in full": "Pagado completo",
    "Tasks & Gigs": "Tareas y changas",
    "Jobs & Repairs": "Trabajos y reparaciones",
    "Driving & Delivery": "Manejo y entregas",
    "Shop & Sales": "Tienda y ventas",
    "Lending & Susu": "Préstamos y susu",
    "Other Work": "Otro trabajo",
    "Platform jobs, tips, travel": "Trabajos de plataforma, propinas, viajes",
    "Materials, advances, job sites": "Materiales, anticipos, sitios de trabajo",
    "Trips, fuel, fares": "Viajes, combustible, tarifas",
    "Daily sales and stock": "Ventas diarias e inventario",
    "Track loans and repayments": "Registra préstamos y pagos",
    "General work tracking": "Seguimiento general de trabajo",
    "Income": "Ingreso",
    "Expense": "Gasto",
    "Advance": "Anticipo",
    "Repayment": "Reembolso",
    "I lent": "Presté",
    "Log jobs to see earnings insights.": "Registra trabajos para ver análisis de ganancias.",
    "Avg kept / job": "Prom. que te quedas / trabajo",
    "Still owed": "Aún te deben",
    "%lld paid": "%lld pagados",
    "%lld open": "%lld abiertos",
    "Waiting on payment": "Esperando pago",
    "You owe": "Debes",
    "Spent this month": "Gastado este mes",
    "Made this month": "Ingresos este mes",
    "Person": "Persona",
    "All tracked jobs are paid. Nice work.": "Todos los trabajos registrados están pagados. Bien hecho.",
    "Track profit and waiting balances at a glance.": "Ve ganancia y saldos pendientes de un vistazo.",
    "Remove photo": "Quitar foto",
    "Contact QR code": "Código QR de contacto",
    "Jobs": "Trabajos",
    "Clear filters": "Borrar filtros",
}

def main() -> None:
    data = {k: {"es-419": v, "es-ES": v} for k, v in PAIRS.items()}
    OUT.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Wrote {len(data)} keys to {OUT}")


if __name__ == "__main__":
    main()
