#!/usr/bin/env python3
"""Build and merge Phase 3 format-string translations."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CATALOG = ROOT / "BuxMuse/Localizable.xcstrings"
OUT = ROOT / "docs/localization/phase3-format-translations.json"

# (es-419, es-ES) — preserve all format specifiers exactly
T: dict[str, tuple[str, str]] = {
    "%": ("%", "%"),
    "%@ %@": ("%1$@ %2$@", "%1$@ %2$@"),
    "%@ %@ · %@": ("%1$@ · %2$@", "%1$@ · %2$@"),
    "%@ (%@)": ("%1$@ (%2$@)", "%1$@ (%2$@)"),
    "%@ / %@h": ("%1$@ / %2$@h", "%1$@ / %2$@h"),
    "%@ Cash": ("Efectivo %@", "Efectivo %@"),
    "%@ Portfolio": ("Portafolio %@", "Cartera %@"),
    "%@ Wallet": ("Billetera %@", "Monedero %@"),
    "%@ color": ("Color %@", "Color %@"),
    "%@ hours": ("%@ horas", "%@ horas"),
    "%@ of %@": ("%1$@ de %2$@", "%1$@ de %2$@"),
    "%@ · %@": ("%1$@ · %2$@", "%1$@ · %2$@"),
    "%@ · %@ (%@)": ("%1$@ · %2$@ (%3$@)", "%1$@ · %2$@ (%3$@)"),
    "%@ · %lldd": ("%1$@ · %2$lldd", "%1$@ · %2$lldd"),
    "%@ · typical %@": ("%1$@ · típico %2$@", "%1$@ · típico %2$@"),
    "%@ — %@%%": ("%1$@ — %2$@%%", "%1$@ — %2$@%%"),
    "%@%lld°": ("%1$@%2$lld°", "%1$@%2$lld°"),
    "%@, open color picker": ("%@, abrir selector de color", "%@, abrir selector de color"),
    "%@. %@. %lld percent.": ("%1$@. %2$@. %3$lld por ciento.", "%1$@. %2$@. %3$lld por ciento."),
    "%@/%@h": ("%1$@/%2$@h", "%1$@/%2$@h"),
    "%@/hr": ("%@/h", "%@/h"),
    "%@:": ("%@:", "%@:"),
    "%lld": ("%lld", "%lld"),
    "%lld Active • %lld%% of total": ("%1$lld activos • %2$lld%% del total", "%1$lld activos • %2$lld%% del total"),
    "%lld Categories · Target: %@": ("%1$lld categorías · Meta: %2$@", "%1$lld categorías · Objetivo: %2$@"),
    "%lld active · %lld overrun risk": ("%1$lld activos · %2$lld en riesgo de exceso", "%1$lld activos · %2$lld en riesgo de exceso"),
    "%lld countries": ("%lld países", "%lld países"),
    "%lld days": ("%lld días", "%lld días"),
    "%lld designs": ("%lld diseños", "%lld diseños"),
    "%lld h": ("%lld h", "%lld h"),
    "%lld invoice(s)": ("%lld factura(s)", "%lld factura(s)"),
    "%lld items": ("%lld ítems", "%lld ítems"),
    "%lld m": ("%lld m", "%lld m"),
    "%lld milestone(s)": ("%lld hito(s)", "%lld hito(s)"),
    "%lld open": ("%lld abiertas", "%lld abiertas"),
    "%lld paid": ("%lld pagadas", "%lld pagadas"),
    "%lld result%@": ("%1$lld resultado%2$@", "%1$lld resultado%2$@"),
    "%lld time entries logged": ("%lld entradas de tiempo registradas", "%lld entradas de tiempo registradas"),
    "%lld total · %lld this month": ("%1$lld total · %2$lld este mes", "%1$lld total · %2$lld este mes"),
    "%lld transactions": ("%lld transacciones", "%lld transacciones"),
    "%lld%%": ("%lld%%", "%lld%%"),
    "%lld/10": ("%lld/10", "%lld/10"),
    "%lld/100": ("%lld/100", "%lld/100"),
    "%lldd": ("%lldd", "%lldd"),
    "%lldh": ("%lldh", "%lldh"),
    "%lldm": ("%lldm", "%lldm"),
    "+%@": ("+%@", "+%@"),
    "+%@%%": ("+%@%%", "+%@%%"),
    "+%lld more": ("+%lld más", "+%lld más"),
    "6-Month Emergency target: %@": ("Meta de emergencia 6 meses: %@", "Meta de emergencia 6 meses: %@"),
    "Add %@": ("Agregar %@", "Añadir %@"),
    "Advance left: %@": ("Anticipo restante: %@", "Anticipo restante: %@"),
    "After %@": ("Después de %@", "Después de %@"),
    "After: %@": ("Después: %@", "Después: %@"),
    "Agreed %@": ("Acordado %@", "Acordado %@"),
    "Almost there — about %lld min left on your plan.": ("Casi listo — unos %lld min restantes en tu plan.", "Casi listo — unos %lld min restantes en tu plan."),
    "Already logged: %@": ("Ya registrado: %@", "Ya registrado: %@"),
    "Anxiety count: %lld": ("Conteo de ansiedad: %lld", "Conteo de ansiedad: %lld"),
    "Avg. time to payment: %lld days": ("Tiempo prom. al pago: %lld días", "Tiempo prom. al pago: %lld días"),
    "Cash (%@)": ("Efectivo (%@)", "Efectivo (%@)"),
    "Current %@ Cash in Wallet": ("Efectivo %@ actual en billetera", "Efectivo %@ actual en monedero"),
    "Deductible: %@": ("Deducible: %@", "Deducible: %@"),
    "Default tax rate %": ("Tasa impositiva predet. %", "Tasa impositiva predet. %"),
    "Delay Risk: %@": ("Riesgo de demora: %@", "Riesgo de demora: %@"),
    "Delete %lld": ("Eliminar %lld", "Eliminar %lld"),
    "Due: %@": ("Vence: %@", "Vence: %@"),
    "ESTIMATED VALUE (%@)": ("VALOR ESTIMADO (%@)", "VALOR ESTIMADO (%@)"),
    "Effective rate %lld%% on recorded income": ("Tasa efectiva %lld%% sobre ingresos registrados", "Tasa efectiva %lld%% sobre ingresos registrados"),
    "Ended %@": ("Finalizó %@", "Finalizó %@"),
    "Est. allowance: %@": ("Asignación est.: %@", "Asignación est.: %@"),
    "Estimated runway based on your %@ monthly burn rate.": ("Pista estimada según tu quema mensual de %@.", "Pista estimada según tu quema mensual de %@."),
    "Fill from %@": ("Rellenar desde %@", "Rellenar desde %@"),
    "Fix: %@": ("Corregir: %@", "Corregir: %@"),
    "Forecast: %@ Risk": ("Pronóstico: riesgo %@", "Pronóstico: riesgo %@"),
    "Header: %@ · Background: %@ · Template: %@": ("Encabezado: %1$@ · Fondo: %2$@ · Plantilla: %3$@", "Encabezado: %1$@ · Fondo: %2$@ · Plantilla: %3$@"),
    "Health Score: %lld%%": ("Puntaje de salud: %lld%%", "Puntaje de salud: %lld%%"),
    "Health · %@": ("Salud · %@", "Salud · %@"),
    "Health: %lld%%": ("Salud: %lld%%", "Salud: %lld%%"),
    "INCOME & DEDUCTIONS (%@)": ("INGRESOS Y DEDUCCIONES (%@)", "INGRESOS Y DEDUCCIONES (%@)"),
    "Impact on '%@'": ("Impacto en '%@'", "Impacto en '%@'"),
    "Irregular: %@": ("Irregular: %@", "Irregular: %@"),
    "Issued: %@": ("Emitido: %@", "Emitido: %@"),
    "LTV %@ · Health %lld%%": ("LTV %1$@ · Salud %2$lld%%", "LTV %1$@ · Salud %2$lld%%"),
    "LTV: %@": ("LTV: %@", "LTV: %@"),
    "Lap %lld": ("Vuelta %lld", "Vuelta %lld"),
    "Last: %@": ("Último: %@", "Último: %@"),
    "Late Risk Detected. Awaiting payment speed estimated at %lld days.": ("Riesgo de demora detectado. Pago estimado en %lld días.", "Riesgo de demora detectado. Pago estimado en %lld días."),
    "Level %lld/10": ("Nivel %lld/10", "Nivel %lld/10"),
    "Live Preview · %@": ("Vista previa · %@", "Vista previa · %@"),
    "Local notification %lld day%@ before renewal.": ("Notificación local %1$lld día%2$@ antes de renovar.", "Notificación local %1$lld día%2$@ antes de renovar."),
    "Log %@ and stop": ("Registrar %@ y detener", "Registrar %@ y detener"),
    'Matching "%@"': ('Coincidencias con "%@"', 'Coincidencias con "%@"'),
    "More colors for %@": ("Más colores para %@", "Más colores para %@"),
    "Next Renewal: %@": ("Próxima renovación: %@", "Próxima renovación: %@"),
    "Next due: %@ · %@": ("Próximo vencimiento: %1$@ · %2$@", "Próximo vencimiento: %1$@ · %2$@"),
    "Paid %@": ("Pagado %@", "Pagado %@"),
    "Payment Terms: %lld Days": ("Plazo de pago: %lld días", "Plazo de pago: %lld días"),
    "Photos: %@": ("Fotos: %@", "Fotos: %@"),
    "Planned time: %@": ("Tiempo planificado: %@", "Tiempo planificado: %@"),
    "Preview: %@": ("Vista previa: %@", "Vista previa: %@"),
    "Qty %@ · %@": ("Cant. %1$@ · %2$@", "Cant. %1$@ · %2$@"),
    "Rate %": ("Tarifa %", "Tarifa %"),
    "Recommended: %@": ("Recomendado: %@", "Recomendado: %@"),
    "Reliability: %lld%%": ("Confiabilidad: %lld%%", "Confiabilidad: %lld%%"),
    "Review %@ preset": ("Revisar preset %@", "Revisar preset %@"),
    "Revisions: %lld/%lld": ("Revisiones: %1$lld/%2$lld", "Revisiones: %1$lld/%2$lld"),
    "Runway %@": ("Pista %@", "Pista %@"),
    "Same trip home — adds a second log with From ↔ To swapped (%@ mi each way).": ("Mismo viaje de vuelta — agrega un segundo registro con Origen ↔ Destino invertidos (%@ mi por tramo).", "Mismo viaje de vuelta — añade un segundo registro con Origen ↔ Destino invertidos (%@ mi por tramo)."),
    "Save %@": ("Ahorra %@", "Ahorra %@"),
    "Save %@/mo": ("Ahorra %@/mes", "Ahorra %@/mes"),
    "Scale: %@": ("Escala: %@", "Escala: %@"),
    "See all %lld designs": ("Ver los %lld diseños", "Ver los %lld diseños"),
    "Shown as %@ · %@": ("Mostrado como %1$@ · %2$@", "Mostrado como %1$@ · %2$@"),
    "Signed · %@": ("Firmado · %@", "Firmado · %@"),
    "Sleep %@h": ("Sueño %@h", "Sueño %@h"),
    "Sleep: %@ hrs": ("Sueño: %@ h", "Sueño: %@ h"),
    "Spent %@": ("Gastado %@", "Gastado %@"),
    "Status: %@": ("Estado: %@", "Estado: %@"),
    "Stress expenses: %lld": ("Gastos por estrés: %lld", "Gastos por estrés: %lld"),
    "Target: %@": ("Meta: %@", "Objetivo: %@"),
    "Tax Health · %@ risk": ("Salud fiscal · riesgo %@", "Salud fiscal · riesgo %@"),
    "Template: %@": ("Plantilla: %@", "Plantilla: %@"),
    "Top: %@ (%@ projected profit)": ("Top: %1$@ (%2$@ ganancia proyectada)", "Top: %1$@ (%2$@ beneficio proyectado)"),
    "Total spent (%@)": ("Total gastado (%@)", "Total gastado (%@)"),
    "Total: %@": ("Total: %@", "Total: %@"),
    "Updated %@": ("Actualizado %@", "Actualizado %@"),
    "Use %@": ("Usar %@", "Usar %@"),
    "Viewing: %@": ("Viendo: %@", "Viendo: %@"),
    "Waiting %@": ("Esperando %@", "Esperando %@"),
    "Waiting: %@": ("En espera: %@", "En espera: %@"),
    "Weekly subs: %@": ("Suscripciones semanales: %@", "Suscripciones semanales: %@"),
    "When paid: keep %@": ("Al pagar: conserva %@", "Al pagar: conserva %@"),
    "Work %@h": ("Trabajo %@h", "Trabajo %@h"),
    "Work logged: %@ hrs": ("Trabajo registrado: %@ h", "Trabajo registrado: %@ h"),
    "Workload %@h vs project time %@h · Scope alerts %lld": ("Carga %1$@h vs proyecto %2$@h · Alertas de alcance %3$lld", "Carga %1$@h vs proyecto %2$@h · Alertas de alcance %3$lld"),
    "Your recurring subscriptions account for roughly %@ of your overall spending. Taking advantage of multi-month prepayments could unlock up to 15%% in annual savings across active plans.": ("Tus suscripciones recurrentes representan ~%@ de tu gasto. Pagos anticipados multimes podrían ahorrarte hasta 15%% anual en planes activos.", "Tus suscripciones recurrentes representan ~%@ de tu gasto. Pagos anticipados multimes podrían ahorrarte hasta 15%% anual en planes activos."),
    "~%@h to finish at current pace": ("~%@h para terminar al ritmo actual", "~%@h para terminar al ritmo actual"),
    "↑ %@%% Increase": ("↑ %@%% aumento", "↑ %@%% aumento"),
    "↓ %@%% Decrease": ("↓ %@%% disminución", "↓ %@%% disminución"),
    "Mode: %@ · %lld profiles": ("Modo: %1$@ · %2$lld perfiles", "Modo: %1$@ · %2$lld perfiles"),
    "Alerts, bill reminders (%@)": ("Alertas, recordatorios de facturas (%@)", "Alertas, recordatorios de facturas (%@)"),
    "Profile": ("Perfil", "Perfil"),
    "Profiles": ("Perfiles", "Perfiles"),
    "On": ("Activado", "Activado"),
    "Off": ("Desactivado", "Desactivado"),
}


def main() -> None:
    keys = (ROOT / "docs/localization/phase3-format-keys.txt").read_text().splitlines()
    out = {k: {"es-419": T[k][0], "es-ES": T[k][1]} for k in keys if k in T}
    missing = [k for k in keys if k not in T]
    OUT.write_text(json.dumps(out, indent=2, ensure_ascii=False) + "\n")
    print(f"wrote {len(out)}, missing dict entries: {len(missing)}")
    if missing:
        print(missing)


if __name__ == "__main__":
    main()
